version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: fitnesstracker_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fitnesstrackerdb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: fitnesstracker_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
  fitness-app:
    build:
      context: .               # корень проекта, где лежит Dockerfile
      dockerfile: Dockerfile   # ваш многоступенчатый Dockerfile
    image: hpclab/fitness-tracker:latest
    container_name: fitnesstracker_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fitnesstrackerdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password