version: '3.8'

services:
  fitness-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hpclab/fitness-tracker:latest
    container_name: fitnesstracker_app
    ports:
      - "${APP_PORT:-8080}:8080"
    cpus: "${APP_CPU_LIMIT:-2}"
    mem_limit: "${APP_MEM_LIMIT:-512M}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://10.60.3.26:${DB_PORT:-5432}/${DB_NAME:-yarbd}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-postgres}
      # Tomcat: max threads
      SERVER_TOMCAT_MAX_THREADS: "${MAX_THREADS:-200}"

      # Отключаем SQL-логи Hibernate
      SPRING_JPA_SHOW_SQL: "${SHOW_SQL:-false}"
