spring.datasource.url=jdbc:postgresql://${DB_HOST:10.60.3.26}:${DB_PORT:5432}/${DB_NAME:yarbd}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# Порт, на котором будет слушать Additional-сервис
server.port=8081

# URL CRUD-сервиса 
crud.service.url=${CRUD_SERVICE_URL:http://localhost:8080}

